name: 'Deploy'
on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
    tags:
      - '*'

  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
      
  workflow_dispatch:
    inputs:
#      release:
#        description: 'Create Release'
#        required: false
#        default: 'false'
      feature:
        description: 'Deploy Feature'
        required: false
        default: 'false'

jobs:

  check-branch:
    runs-on: ubuntu-latest
    outputs:
      is_hotfix: ${{ steps.set-vars.outputs.is_hotfix }}
    steps:
    - id: set-vars
      run: |
        echo "Checking branch..."
        if [[ "${{ github.ref }}" == "refs/heads/hotfix"* ]]; then
          echo "::set-output name=is_hotfix::true"
        else
          echo "::set-output name=is_hotfix::false"
        fi

    
  gitversion:
    name: 'GitVersion'
    uses: szirmaibence98/templates/.github/workflows/gitversion.yml@main

#  snyk:
#    name: 'Snyk'
#    needs: gitversion
#    uses: szirmaibence98/templates/.github/workflows/snyk.yml@main
#    secrets:
#      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#    with:
#      release: ${{ github.event.inputs.release == 'true' }}
      
#  semgrep:
#    name: 'Semgrep'
#    needs: gitversion
#    uses: szirmaibence98/templates/.github/workflows/semgrep.yml@main
#    with:
#      release: ${{ github.event.inputs.release == 'true' }}
    
  build:
    name: 'Build'
    needs:  
     - gitversion
    uses: szirmaibence98/templates/.github/workflows/dotnet.yml@main
    with:
      dotnet-version: '8.0.x'
      working-directory: 'src'
      release: ${{ github.event.inputs.release == 'true' }}
      
  docker:
    needs: 
     - build
#     - snyk
#     - semgrep
    uses: szirmaibence98/templates/.github/workflows/docker.yml@main
    if: ${{ github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/heads/feature/') && github.event.inputs.feature == 'true') }}
    with:
      image-name: szirmaibence98/testimage
      docker-context: '.'
      release: ${{ github.event.inputs.release == 'true' }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#  trivy:
#    name: 'Trivy'
#    needs: docker
#    uses: szirmaibence98/templates/.github/workflows/trivy.yml@main
#    if: ${{ github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/heads/feature/') && github.event.inputs.feature == 'true') }}



#  opa:
#    name: 'Open Policy Agent'
#    needs: docker
#    if: ${{ github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/heads/feature/') && github.event.inputs.feature == 'true') }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4.1.1
      
#      - name: Install OPA
#        run: |
#          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
#          chmod +x opa
#          sudo mv opa /usr/local/bin/
#      - name: Run OPA Policy Check
#        run: opa eval --format pretty --data policy.rego --input input.json "data.dockerfile.allow"




  helm:
    needs: docker
    uses: szirmaibence98/templates/.github/workflows/helm.yml@main
    if: ${{ github.ref == 'refs/heads/main' || (startsWith(github.ref, 'refs/heads/feature/') && github.event.inputs.feature == 'true') }}
    with:
      release: ${{ github.event.inputs.release == 'true' }}
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}


  deploy-to-dev:
    name: 'Deploy to Development'
    needs: helm
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || (startsWith(github.ref, 'refs/heads/feature/') && github.event.inputs.feature == 'true') }}
    environment: 
      name: dev
    steps:
      - name: Simulate Deployment to Development
        run: echo "Deploying to Development Environment"

  deploy-to-staging:
    name: 'Deploy to Staging'
    needs: helm
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    environment: 
      name: staging
    steps:
      - name: Simulate Deployment to Staging
        run: echo "Deploying to Staging Environment"

  deploy-to-prod:
    name: 'Deploy to Prod'
    needs: [check-branch, deploy-to-staging]
    if: |
      ${{ needs.check-branch.outputs.is_hotfix == 'false' }} || 
      ${{ github.ref == 'refs/heads/hotfix' && needs.check-branch.outputs.is_hotfix == 'true' }}
    runs-on: ubuntu-latest
    environment: 
      name: prod
    steps:
      - name: Simulate Deployment to Production
        run: echo "Deploying to Production Environment"



  create-tag-after-prod:
    name: 'Create Tag After Prod'
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Download version file
        uses: actions/download-artifact@v4.1.4
        with:
          name: version
          path: /tmp
      
      - name: Read version from file
        id: read_version
        run: echo "VERSION=$(cat /tmp/version.txt)" >> $GITHUB_ENV
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create and push tag based on GitVersion
        run: |
          VERSION=${{ env.VERSION }}
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
