name: 'dotNet'
on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'

  workflow_dispatch:
    inputs:
      create-release:
        description: 'Create release'
        required: true
        default: false

jobs:


  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches the complete commit history

      - name: Setup Gitleaks
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Save Gitleaks Results
        if: ${{ always() }}  # Always execute even if previous steps fail
        run: |
          mv results.sarif gitleaks-results-$(date +"%Y%m%d-%H%M%S").sarif
          echo "✅ Gitleaks scan completed"

  
      - name: Summarize Gitleaks Findings
        if: ${{ always() }}
        run: |
          sudo apt-get install jq -y
          SARIF_FILE=$(ls gitleaks-results-*.sarif)
          if [ ! -f "$SARIF_FILE" ]; then
            echo "Gitleaks SARIF file not found. ❌" >> $GITHUB_STEP_SUMMARY
          else
            LEAKS=$(jq '.runs[0].results | if length == 0 then "No leaks found." else map(.ruleId + ": " + .message.text) | .[] end' $SARIF_FILE)
            if [ "$LEAKS" == "No leaks found." ]; then
              echo "$LEAKS" >> $GITHUB_STEP_SUMMARY
            else
              echo "Leaks found:" >> $GITHUB_STEP_SUMMARY
              echo "$LEAKS" | sed 's/^/ - /' >> $GITHUB_STEP_SUMMARY
            fi
          fi

#      - name: Check Gitleaks Results
#        if: ${{ always() }}
#        run: |
#          if [ ! -s "results.sarif" ]; then
#            echo "No leaks detected ✅"
#          else
#            echo "Vulnerabilities found ❌"
#            cat results.sarif
#          fi

#      - name: Upload Gitleaks Results
#        if: ${{ always() }}  # Always execute even if previous steps fail
#        uses: actions/upload-artifact@v2
#        with:
#          name: gitleaks-results
#          path: gitleaks-results-*.sarif  # Uploads all SARIF files matching the pattern




















  
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        with:
          language: dotnet
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN
  
      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true
  
      - name: Save Snyk Results
        if: ${{ always() }}
        run: |
          mv snyk-code.sarif snyk-results-$(date +"%Y%m%d-%H%M%S").sarif
          echo "✅ Snyk scan completed"
  
      - name: Upload Snyk Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: snyk-results
          path: snyk-results-*.sarif

      - name: Summarize Snyk Findings
        if: ${{ always() }}
        run: |
          sudo apt-get install jq -y
          SARIF_FILE=$(ls snyk-results-*.sarif)
          if [ ! -f "$SARIF_FILE" ]; then
            echo "Snyk SARIF file not found. ❌" >> $GITHUB_STEP_SUMMARY
          else
            VULNERABILITIES=$(jq '.runs[0].results | if length == 0 then "No vulnerabilities found." else map(.ruleId + ": " + .message.text) | .[] end' $SARIF_FILE)
            if [ "$VULNERABILITIES" == "No vulnerabilities found." ]; then
              echo "$VULNERABILITIES" >> $GITHUB_STEP_SUMMARY
            else
              echo "Vulnerabilities found:" >> $GITHUB_STEP_SUMMARY
              echo "$VULNERABILITIES" | sed 's/^/ - /' >> $GITHUB_STEP_SUMMARY
            fi
          fi





#      - name: Send Gitleaks Report to Slack
#        if: failure()  # Executes only if Gitleaks scan fails
#        uses: rtCamp/action-slack-notify@v3
#        with:
#          status: failure
#          text: |
#            Gitleaks scan detected potential leaks in the repository. Check the attached report for details.
#          attachments: gitleaks-results-*.sarif
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read    
    container:
      image: returntocorp/semgrep
    steps:
      # Install Semgrep
      - name: Install Semgrep
        run: |
          pip install semgrep
  
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
  
      # Run Semgrep with SARIF output
      - name: Run Semgrep with SARIF output
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"
  
      # Save report as pipeline artifact
      - name: Save report as pipeline artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: report.sarif
          path: report.sarif
  
      # Upload SARIF file to GitHub
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
        if: always()
  
  
      # Install jq and Summarize Semgrep Findings
      - name: Summarize Semgrep Findings
        if: always()
        run: |
          sudo apt-get update && sudo apt-get install jq -y
          if [ ! -f report.sarif ]; then
            echo "Semgrep SARIF file not found. ❌" >> $GITHUB_STEP_SUMMARY
          else
            FINDINGS=$(jq '.runs[0].results | if length == 0 then "No issues found." else map(.ruleId + ": " + .message.text) | .[] end' report.sarif)
            if [ "$FINDINGS" == "No issues found." ]; then
              echo "$FINDINGS" >> $GITHUB_STEP_SUMMARY
            else
              echo "Issues found:" >> $GITHUB_STEP_SUMMARY
              echo "$FINDINGS" | sed 's/^/ - /' >> $GITHUB_STEP_SUMMARY
            fi
          fi

            






  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check if release should be created
        run: |
          if ${{ github.event.inputs.create-release }}; then
            echo "Creating release"
          else
            echo "Not creating release"
          fi

      - name: Example Step
        run: echo "The version is valami"




  gitversion:
    name: 'GitVersion'
    uses: szirmaibence98/templates/.github/workflows/gitversion.yml@main

    
  build:
    name: 'Build'
    needs: gitversion
    uses: szirmaibence98/templates/.github/workflows/dotnet.yml@main
    with:
      dotnet-version: '8.0.x'
      working-directory: 'src' # Optional: specify if your solution file is not in the root directory

      
  docker:
    needs: build
    uses: szirmaibence98/templates/.github/workflows/docker.yml@main
    with:
      image-name: szirmaibence98/testimage
      docker-context: '.'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
