name: 'dotNet'
on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'

  workflow_dispatch:
    inputs:
      create-release:
        description: 'Create release'
        required: true
        default: false

jobs:

  gitleaks:
    name: 'GitLeaks'
    uses: szirmaibence98/templates/.github/workflows/gitleaks.yml@main
 
  gitversion:
    name: 'GitVersion'
    uses: szirmaibence98/templates/.github/workflows/gitversion.yml@main

  snyk:
    name: 'Snyk'
    needs: gitversion
    uses: szirmaibence98/templates/.github/workflows/snyk.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
  semgrep:
    name: 'Semgrep'
    needs: gitversion
    uses: szirmaibence98/templates/.github/workflows/semgrep.yml@main
    
  build:
    name: 'Build'
    needs:  [gitversion, snyk, semgrep]
    uses: szirmaibence98/templates/.github/workflows/dotnet.yml@main
    with:
      dotnet-version: '8.0.x'
      working-directory: 'src'
      
  docker:
    needs: build
    uses: szirmaibence98/templates/.github/workflows/docker.yml@main
    with:
      image-name: szirmaibence98/testimage
      docker-context: '.'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  trivy:
    name: 'Trivy'
    needs: docker
    uses: szirmaibence98/templates/.github/workflows/trivy.yml@main



