name: 'Release'
on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
    tags:
      - '*'

  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
      
  workflow_dispatch:
    inputs:
#      release:
#        description: 'Create Release'
#        required: false
#        default: 'false'
      feature:
        description: 'Deploy Feature'
        required: false
        default: 'false'

jobs:
    


  deploy-to-dev:
    name: 'Deploy to Development'
#    needs: helm
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    environment: 
      name: dev
    steps:
      - name: Simulate Deployment to Development
        run: echo "Deploying to Development Environment"

  deploy-to-staging:
    name: 'Deploy to Staging'
#    needs: deploy-to-dev
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    environment: 
      name: staging
    steps:
      - name: Simulate Deployment to Staging
        run: echo "Deploying to Staging Environment"

  deploy-to-prod:
    name: 'Deploy to Prod'
#    needs: deploy-to-staging
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    environment: 
      name: prod
    steps:
      - name: Simulate Deployment to Staging
        run: echo "Deploying to Staging Environment"


