name: 'Release'
on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
    tags:
      - '*'

  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'hotfix/*'
    paths:
      - 'src/**'
      
  workflow_dispatch:
    inputs:
      feature:
        description: 'Deploy Feature'
        required: false
        default: 'false'

jobs:

  deploy-staging:
    uses: szirmaibence98/templates/.github/workflows/deploy.yml@main
    with:
      environment: dev
      deploy_condition: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
      
  deploy-prod:
    uses: szirmaibence98/templates/.github/workflows/deploy.yml@main
    with:
      environment: dev
      deploy_condition: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/hotfix/') }}
      


